# Generated by Django 3.1.3 on 2020-12-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='createpost',
            name='author',
            field=models.CharField(default='Admin', max_length=100),
        ),
    ]
