# Generated by Django 3.1.3 on 2021-01-26 05:41

import ckeditor_uploader.fields
import datetime
from django.db import migrations
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='createpost',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=datetime.datetime(2021, 1, 26, 5, 41, 53, 654961, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
