# Generated by Django 3.1.3 on 2021-01-26 05:49

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_createpost_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createpost',
            name='body',
        ),
        migrations.AlterField(
            model_name='createpost',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
