# Generated by Django 3.1.3 on 2020-12-28 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_createpost_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
